# Generated by Django 6.0.2 on 2026-02-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominee', '0004_vote_is_locked_vote_locked_at_alter_vote_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_vote_per_poll',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_ip_vote_per_poll',
        ),
    ]
