# Generated by Django 6.0.2 on 2026-02-12 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominee', '0005_remove_vote_unique_user_vote_per_poll_and_more'),
        ('voting', '0004_ballot_remove_headline_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ballot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee_votes', to='voting.ballot'),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee_votes', to='voting.election'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'election', 'ballot'), name='unique_user_vote_per_ballot'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False)), fields=('ip_address', 'election', 'ballot'), name='unique_ip_vote_per_ballot'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll_info',
        ),
    ]
