# Generated by Django 6.0.2 on 2026-02-12 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_headline_require_google_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('question', models.TextField()),
                ('max_selections', models.IntegerField(default=1)),
                ('min_selections', models.IntegerField(default=1)),
                ('allow_write_in', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='headline',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='poll_information',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_info',
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('party', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos')),
                ('order', models.IntegerField(default=0)),
                ('is_write_in', models.BooleanField(default=False)),
                ('votes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.ballot')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('election_type', models.CharField(choices=[('local', 'Local Election'), ('state', 'State Election'), ('national', 'National Election'), ('primary', 'Primary Election'), ('general', 'General Election'), ('special', 'Special Election')], max_length=20)),
                ('voting_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('ranked_choice', 'Ranked Choice'), ('proportional', 'Proportional Representation')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('results_publish_date', models.DateTimeField(blank=True, null=True)),
                ('min_age', models.IntegerField(default=18)),
                ('citizenship_required', models.BooleanField(default=True)),
                ('residency_required', models.BooleanField(default=True)),
                ('voter_registration_required', models.BooleanField(default=True)),
                ('require_mfa', models.BooleanField(default=True)),
                ('require_google_auth', models.BooleanField(default=False)),
                ('allow_vote_changes', models.BooleanField(default=False)),
                ('max_vote_changes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='election_logos')),
                ('header_img', models.ImageField(blank=True, null=True, upload_to='election_headers')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election'),
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_voters', models.IntegerField(default=0)),
                ('encrypted_results', models.TextField()),
                ('results_hash', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_selections', models.TextField()),
                ('selection_hash', models.CharField(max_length=64)),
                ('vote_token', models.CharField(max_length=64, unique=True)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.ballot')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=32, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.vote')),
            ],
        ),
    ]
