# Generated by Django 6.0.2 on 2026-02-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominee', '0006_vote_ballot_vote_election_alter_vote_user_and_more'),
        ('voting', '0004_ballot_remove_headline_creator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headline',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Poll_information',
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('ballot', 'order')},
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status', 'start_date'], name='voting_elec_status_20678c_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['election_type'], name='voting_elec_electio_12e3e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('election', 'order')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'cast_at'], name='voting_vote_electio_c0fd35_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['vote_token'], name='voting_vote_vote_to_9c113b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('election', 'voter')},
        ),
    ]
