# Generated by Django 6.0.2 on 2026-03-06 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_delete_headline_delete_poll_delete_poll_information_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='allowed_email_domains',
            field=models.JSONField(blank=True, default=list, help_text='If set, only these email domains can vote. E.g. ["company.com"]'),
        ),
        migrations.AddField(
            model_name='election',
            name='require_captcha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='require_voter_registration',
            field=models.BooleanField(default=False, help_text='If True, only voters on the EligibleVoter invite list can vote.'),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='public_verification_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='voting.election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.ballot'),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='encrypted_results',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='results_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('ballot', 'voter')},
        ),
        migrations.CreateModel(
            name='EligibleVoter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('invite_token', models.CharField(max_length=64, unique=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_voters', to='voting.election')),
            ],
            options={
                'unique_together': {('election', 'email')},
            },
        ),
        migrations.CreateModel(
            name='VoteChainEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('current_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_entries', to='voting.ballot')),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chain_entry', to='voting.vote')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('ballot', 'sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_sessions', to='voting.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'election')},
            },
        ),
    ]
