# Generated by Django 6.0.2 on 2026-03-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_add_tenant_and_user_tenant'),
        ('voting', '0006_security_models_and_election_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant/organization; null = platform-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to='userauth.tenant'),
        ),
    ]
