# Generated by Django 6.0.2 on 2026-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_add_election_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Display name for this election; defaults to title if blank.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex color e.g. #B45309 for accents; used in election-specific pages.', max_length=7, null=True),
        ),
    ]
