# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_add_election_white_label'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['tenant'], name='voting_elec_tenant__idx'),
        ),
    ]
