# Generated by Django 6.0.2 on 2026-03-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='election',
            name='voting_elec_tenant__idx',
        ),
    ]
