# Generated by Django 6.0.2 on 2026-03-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_organisation_election_organisation_orgmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='seats',
            field=models.IntegerField(blank=True, default=1, help_text='For PR: number of seats to allocate. Default 1.', null=True),
        ),
    ]
