# Generated by Django 6.0.2 on 2026-03-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('plan', models.CharField(blank=True, help_text='e.g. free, pro, enterprise', max_length=40, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to; null = platform-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='userauth.tenant'),
        ),
    ]
