# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_add_tenant_and_user_tenant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['timestamp'], name='userauth_sec_timestamp_idx'),
        ),
    ]
