# Generated by Django 6.0.2 on 2026-03-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_securitylog_timestamp_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securitylog',
            name='userauth_sec_timestamp_idx',
        ),
    ]
