# Generated by Django 6.0.2 on 2026-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_remove_securitylog_userauth_sec_timestamp_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship_country',
            field=models.CharField(blank=True, choices=[('', '-- Select country of citizenship --'), ('US', 'United States'), ('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('EG', 'Egypt'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GR', 'Greece'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JP', 'Japan'), ('KE', 'Kenya'), ('MY', 'Malaysia'), ('MX', 'Mexico'), ('NL', 'Netherlands'), ('NG', 'Nigeria'), ('NO', 'Norway'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RO', 'Romania'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('RS', 'Serbia'), ('SG', 'Singapore'), ('ZA', 'South Africa'), ('KR', 'South Korea'), ('ES', 'Spain'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('TW', 'Taiwan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('VE', 'Venezuela'), ('VN', 'Vietnam')], help_text='Country of citizenship (used to prove citizenship for voting).', max_length=2, null=True),
        ),
    ]
