# Generated by Django 6.0.2 on 2026-03-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_add_citizenship_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('election_admin', 'Election Administrator'), ('org_admin', 'Organisation Admin'), ('monitor', 'Monitor'), ('auditor', 'Auditor'), ('super_admin', 'Super Admin')], default='voter', max_length=20),
        ),
    ]
