# Generated by Django 6.0.3 on 2026-03-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_add_role_change_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('password_change', 'Password Change'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('phone_verified', 'Phone Verified'), ('phone_otp_sent', 'Phone OTP Sent'), ('phone_number_updated', 'Phone Number Updated'), ('vote_cast', 'Vote Cast'), ('vote_duplicate_blocked', 'Duplicate Vote Blocked'), ('vote_eligibility_denied', 'Eligibility Check Failed'), ('vote_captcha_failed', 'CAPTCHA Verification Failed'), ('vote_ratelimit_hit', 'Vote Rate Limit Hit'), ('suspicious_ip', 'Suspicious IP Activity'), ('election_closed', 'Election Closed'), ('result_published', 'Results Published'), ('result_accessed', 'Results Accessed'), ('admin_action', 'Admin Action'), ('role_change', 'Role Change'), ('invite_sent', 'Voter Invite Sent'), ('invite_token_used', 'Invite Token Used')], max_length=32),
        ),
    ]
